### ISSUE TITLE
"ordinal arguments" error on libsass

### ISSUE THREAD

**Issue by jedfoster** [davidkpiano/sassdash#14]
I'm trying to add this library to sassmeister.com and my tests are failing on the Libsass compiler.

I tested against two versions of node-sass, with similar results.
## node-sass@3.0.0-alpha.0

```
$ cat test/fixtures/Sassdash.scss | node-sass --include-path lib/sass_modules/vendor/sassdash/scss/
{
  "message": "optional parameters may not be combined with variable-length parameters",
  "column": 58,
  "line": 44,
  "file": "lib/sass_modules/vendor/sassdash/scss/helpers/_call.scss",
  "status": 1
}
```
## node-sass@3.0.0-beta.7

```
$ cat test/fixtures/Sassdash.scss | node-sass --include-path lib/sass_modules/vendor/sassdash/scss/
{
  "message": "ordinal arguments must precede variable-length arguments",
  "column": 43,
  "line": 64,
  "file": "lib/sass_modules/vendor/sassdash/scss/helpers/_call.scss",
  "status": 1
}
```

``` scss
// test/fixtures/Sassdash.scss

@import "sassdash";

$maps: (
  ('name': 'barney', 'age': 36),
  ('name': 'fred', 'age': 40)
);

.test {
  debug: _pluck($maps, 'name'); // ('barney', 'fred')
}
```

Ruby Sass 3.4.12 works as expected.
