### ISSUE TITLE
pow() function returns incorrect values with fractional exponents

### ISSUE THREAD

**Issue by lunelson** [davidkpiano/sassdash#21]
This

``` scss
.test {
  pow: pow(1.5, -2/2);
  pow: pow(1.5, -1/2);
  pow: pow(1.5, 0/2);
  pow: pow(1.5, 1/2);
  pow: pow(1.5, 2/2);
}
```

return this

``` css
.test {
  pow: 0.66667;
  pow: 0.44444;
  pow: 1;
  pow: 2.25;
  pow: 1.5;
}
```

but should return this

``` css
.test {
  pow: 0.66667;
  pow: 0.8165;
  pow: 1;
  pow: 1.22474;
  pow: 1.5;
}
```

see the implementation in https://github.com/terkel/mathsass for a more robust function
