### ISSUE TITLE
Consider changing API of `_get()` and `_set()` to use rest arguments

### ISSUE THREAD

**Issue by lunelson** [davidkpiano/sassdash#24]
I suggest changing the argument pattern of `_get()` and `_set()` to use rest-arguments—i.e. comma-separated keys rather than a `list` of keys. The unique characteristics of SassScript `maps` mean there is a potential logical conflict in using a list of keys, since a list itself may also be a key. [For this reason the comma-separated approach will also be implemented in a future version of core Sass](https://github.com/sass/sass/issues/1739#issuecomment-122435753).

Consider how rest-args here allow `get()` to handle any type of key. Function is from [my own library](https://github.com/lunelson/sass-maps-plus) which also implements the same kind of arguments for `merge()` and `set()`:

``` scss
@import "sass-maps-plus";

$map1: (
  alpha: (
    beta: (
      gamma: 3
    )
  )
);

$map2: (
  (alpha beta gamma): 3
);

.debug {
  map1: inspect(get($map1, alpha, beta, gamma));
  map2: inspect(get($map2, alpha beta gamma));
}
```

``` css
.debug {
  map1: 3;
  map2: 3;
}
```

gist: http://sassmeister.com/gist/f591401c7cd1308158aa
