### ISSUE TITLE
_get using unquoted map-keys

### ISSUE THREAD

**Issue by mil** [davidkpiano/sassdash#25]
Thanks again for the great library.

As far as I can tell (from looking at the tests), `_get` is only designed to work with quoted map keys. Are there plans or a stance for being able to support unquoted map-keys for `_get` and other sassdash functions?

**Comment by davidkpiano** [comment]
Hey, @mil! Much thanks!

Is this what you mean? http://sassmeister.com/gist/950fbbb508a1caa5d4a4

``` scss
$map: (
  blue: 'test',
  3: 'test number',
  #C0FF33: 'test color',
  'string': 'test string'
);

test {
  test: _get($map, blue);
  test: _get($map, 3); 
  test: _get($map, #C0FF33);
  test: _get($map, string); // unquoted
}
```
