### ISSUE TITLE
TODO: add comparison functions and syntax

### ISSUE THREAD

**Issue by davidkpiano** [davidkpiano/sassdash#4]
Since Sass does not have an easy way to define anonymous callbacks, I'm considering adding **comparison functions** for both the standard API and the shifted argument syntax.

**SYNTAX:** `_comparator($first, $second, $predicate: __identity);`

``` scss
$foo: _gt(3, 1); // true
$foo: _gte(-3, 3, abs); // true
$foo: _lt(white, black, darkness); // true
$foo: _lte(2.718, 3, ceil); // true
$foo: _eq(white, black, darken 100%); // true (using shifted arg syntax)
```

**Within shifted argument syntax:**

``` scss
// Same as:
// @function lightness-lt-50p($value) { @return _lt(lightness($value), 50%); }
// $light-colors: _filter($colors, lightness-lt-50p);
$light-colors: _filter($colors, lightness _lt 50%);
```
